name: Nightly Build
permissions:
  contents: read

on:
  schedule: # runs on the default branch: master
    - cron: "0 2 * * *" # run at 2 AM UTC
  workflow_dispatch:

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit

    permissions:
      contents: read
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours" ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Call Build
    needs: check_date
    if: |
      ${{ needs.check_date.outputs.should_run != 'false' }}
      && startsWith(github.ref, 'refs/heads/feature/cheap2')
      && ! contains(github.head_ref, 'refs/heads/chore/')
    uses: vondraussen/evcc/.github/workflows/default.yml@feature/cheap2
    permissions:
      contents: read
      actions: write

  docker:
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/evc
    name: Publish Docker :nightly
    needs:
      - call-build-workflow
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: refs/heads/feature/cheap2
          fetch-depth: 0
          persist-credentials: false

      - name: Get dist from cache
        uses: actions/cache/restore@v5
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.sha }}-dist

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=nightly
            type=raw,value=nightly.{{date 'YYYYMMDD'}}-{{sha}}

      - name: Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
